services:
  - type: web
    name: deepfake-check
    env: docker
    repo: https://github.com/Ruth44/deepfake-check
    branch: main
    rootDir: III__Flask-Web-Application  # ğŸ‘ˆğŸ½ tells Render to go into that folder
    plan: free
